### PR TITLE
Updated to cljx 3.0

### PR DESCRIPTION
**Pull request by jeluard**

### CODE REVIEW

**Comment by davidsantiago** [comment]
I pulled these in, I'm thinking I'm pretty happy with how it's all shaping up, now that cljx 3 is available. Will do a release soon. Is there some special way to distribute clojurescript? Seems to get put right into the jar with the clojure version, so hopefully that works fine and no special work is needed.

Thanks, 
   David

**Comment by jeluard** [comment]
No you are right, there is nothing special needed to distribute ClojureScript code.

**Comment by davidsantiago** [comment]
OK, unless you give me a reason not to in a few hours, I'll cut a pathetic 0.5 release.

**Comment by jeluard** [comment]
Sounds perfect to me!

**Comment by davidsantiago** [comment]
A few hours, a day, whatever. I'm traveling and didn't quite get to it yesterday, so sorry about that. But I released 0.5.0 just now. Thanks for being so great to collaborate with!

**Comment by jeluard** [comment]
Great, thanks!

**Pull request merged**
